### ISSUE TITLE
Next major version: code cleanup, return types, Symfony 6...

### ISSUE THREAD

**Issue by jmsche** [leapt/core-bundle#8]
As Symfony 6 may add return types, it will also require a new major version.

It's the perfect time to also add return types everywhere it's possible. Maybe even add a constraint in code analyzers about it?

The new major version _should_ be released in November or early December, so phpstan will also be available as 1.x version.

To do:

- [x] Create a 3.x branch, and rename master branch to 4.x
- [x] Support Symfony 6 (started in #7)
- [x] Clean up code (remove useless comments, add return types, constructor property promotion...) => #10
- [x] Drop Symfony 4.x support => #12 
- [x] Set min Symfony version to 5.4 => #12 
- [x] Drop PHP 7.4 support => #10
- [x] Upgrade phpstan to 1.0 (expected release: November, 1st) => #16 
- [x] Improve phpstan level? (optional) => #16 
- [x] Declare strict types everywhere? (optional) => #13 
- [x] Update README & docs => #18 
- [x] Make the existing annotations/attributes, PHP attributes only => #17 
- [x] Add .gitattributes => #14 
- [x] Remove phpunit-bridge and use phpunit instead => #15

**Comment by jmsche** [comment]
Final checks coming, then a stable release.

**Comment by jmsche** [comment]
v4.0.0 has been released :)
